services:
  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    depends_on:
      - database

  frontend:
    build: ./frontend
    depends_on:
      - backend

volumes:
  mongo-data:
